"""initial_schema

Revision ID: 5bf7a5801c47
Revises: 
Create Date: 2026-03-27 20:48:29.075266
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bf7a5801c47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_change_codes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('new_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('new_device_name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.SmallInteger(), nullable=False),
    sa.Column('fail_count', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_change_codes', schema=None) as batch_op:
        batch_op.create_index('idx_dcc_user_product', ['user_id', 'product_id'], unique=False)

    op.create_table('email_verification_codes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_codes', schema=None) as batch_op:
        batch_op.create_index('idx_email_purpose', ['email', 'purpose'], unique=False)

    op.create_table('products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('security_limits',
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('fail_count', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_fail_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('limit_type', 'identifier')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.Column('is_admin', sa.SmallInteger(), nullable=False),
    sa.Column('email_verified', sa.SmallInteger(), nullable=False),
    sa.Column('email_notified_7d', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_email', ['email'], unique=False)

    op.create_table('account_migration_requests',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_credential', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by', sa.BigInteger(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activation_codes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.create_index('idx_activation_code', ['code'], unique=False)

    op.create_table('admin_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.create_index('idx_admin_created', ['admin_user_id', 'created_at'], unique=False)

    op.create_table('device_rebind_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('old_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('new_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('old_device_name', sa.String(length=255), nullable=True),
    sa.Column('new_device_name', sa.String(length=255), nullable=True),
    sa.Column('rebind_type', sa.String(length=20), nullable=True),
    sa.Column('operator_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('download_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('completed', sa.SmallInteger(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_logs', schema=None) as batch_op:
        batch_op.create_index('idx_dl_type_created', ['download_type', 'created_at'], unique=False)
        batch_op.create_index('idx_dl_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('license_codes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('license_type', sa.String(length=20), nullable=False),
    sa.Column('duration_months', sa.SmallInteger(), nullable=True),
    sa.Column('is_trial', sa.SmallInteger(), nullable=False),
    sa.Column('specialty_ids', sa.JSON(), nullable=True),
    sa.Column('is_activated', sa.SmallInteger(), nullable=False),
    sa.Column('activated_by', sa.BigInteger(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_note', sa.Text(), nullable=True),
    sa.Column('created_by_admin', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('license_codes', schema=None) as batch_op:
        batch_op.create_index('idx_license_code', ['code'], unique=False)
        batch_op.create_index('idx_license_product', ['product_id'], unique=False)

    op.create_table('specialty_version_policy',
    sa.Column('specialty_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('force_min_version', sa.String(length=20), nullable=True),
    sa.Column('force_max_version', sa.String(length=20), nullable=True),
    sa.Column('policy_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('specialty_id', 'product_id')
    )
    op.create_table('user_licenses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('is_trial', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.Column('token_created_at', sa.DateTime(), nullable=True),
    sa.Column('rebind_count', sa.SmallInteger(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_ip', sa.String(length=45), nullable=True),
    sa.Column('reported_specialties', sa.JSON(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product')
    )
    with op.batch_alter_table('user_licenses', schema=None) as batch_op:
        batch_op.create_index('idx_access_token', ['access_token'], unique=False)
        batch_op.create_index('idx_license_expires_at', ['expires_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_token', ['session_token'], unique=False)
        batch_op.create_index('idx_session_user_id', ['user_id'], unique=False)

    op.create_table('user_specialties',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('specialty_id', sa.String(length=50), nullable=False),
    sa.Column('license_code_id', sa.BigInteger(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_code_id'], ['license_codes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', 'specialty_id', name='uq_user_product_specialty')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_specialties')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_session_user_id')
        batch_op.drop_index('idx_session_token')

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_licenses', schema=None) as batch_op:
        batch_op.drop_index('idx_license_expires_at')
        batch_op.drop_index('idx_access_token')

    op.drop_table('user_licenses')
    op.drop_table('specialty_version_policy')
    with op.batch_alter_table('license_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_license_product')
        batch_op.drop_index('idx_license_code')

    op.drop_table('license_codes')
    with op.batch_alter_table('download_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_dl_user_created')
        batch_op.drop_index('idx_dl_type_created')

    op.drop_table('download_logs')
    op.drop_table('device_rebind_logs')
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_admin_created')

    op.drop_table('admin_logs')
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_activation_code')

    op.drop_table('activation_codes')
    op.drop_table('account_migration_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_email')

    op.drop_table('users')
    op.drop_table('security_limits')
    op.drop_table('products')
    with op.batch_alter_table('email_verification_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_email_purpose')

    op.drop_table('email_verification_codes')
    with op.batch_alter_table('device_change_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_dcc_user_product')

    op.drop_table('device_change_codes')
    # ### end Alembic commands ###
