"""add_duration_days_to_license_codes

Revision ID: fd3929d0f150
Revises: 5bf7a5801c47
Create Date: 2026-03-29 08:41:57.276235
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd3929d0f150'
down_revision: Union[str, None] = '5bf7a5801c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_codes', schema=None) as batch_op:
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###
