server {
    listen 443 ssl;
    server_name medcomm.linscio.com.cn;
    ssl_certificate     /etc/nginx/ssl/medcomm.linscio.com.cn.pem;
    ssl_certificate_key /etc/nginx/ssl/medcomm.linscio.com.cn.key;

    root /www/wwwroot/linscio-release/medcomm;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
