server {
    listen 443 ssl;
    server_name medcomm.linscio.com.cn;
    ssl_certificate     /www/server/panel/vhost/cert/medcomm.linscio.com.cn/fullchain.pem;
    ssl_certificate_key /www/server/panel/vhost/cert/medcomm.linscio.com.cn/privkey.pem;

    root /www/wwwroot/linscio-release/medcomm;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
