server {
    listen 443 ssl;
    server_name portal.linscio.com.cn;
    ssl_certificate     /etc/nginx/ssl/portal.linscio.com.cn.pem;
    ssl_certificate_key /etc/nginx/ssl/portal.linscio.com.cn.key;

    root /home/linscio/portal;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
