server {
    listen 443 ssl;
    server_name www.linscio.com.cn;
    ssl_certificate     /etc/nginx/ssl/www.linscio.com.cn.pem;
    ssl_certificate_key /etc/nginx/ssl/www.linscio.com.cn.key;

    root /home/linscio/www;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
